apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry-ui
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry-ui
  template:
    metadata:
      labels:
        app: registry-ui
    spec:
      containers:
        - name: registry-ui
          image: joxit/docker-registry-ui:latest
          ports:
            - containerPort: 80
          env:
            - name: REGISTRY_URL
              value: http://registry.{{ .Values.namespace }}.svc.cluster.local:80
            - name: DELETE_IMAGES
              value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: registry-ui
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: registry-ui
  ports:
    - port: 80
      targetPort: 80
