apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry-ui
  namespace: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry-ui
  template:
    metadata:
      labels:
        app: registry-ui
    spec:
      containers:
        - name: registry-ui
          image: joxit/docker-registry-ui:latest
          ports:
            - containerPort: 80
          env:
            - name: REGISTRY_URL
              value: "" # kosongkan, supaya browser tidak akses langsung registry
            - name: NGINX_PROXY_PASS_URL
              value: http://registry:5000 # nama service registry kamu
            - name: DELETE_IMAGES
              value: "true"
